version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - .:/ap  # Mount the current directory into the container
    environment:
      - NODE_ENV=development  # Set the Node.js environment to development
    networks:
      - mail
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "444:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./ssl/:/etc/ssl/
  #   depends_on:
  #     - web

networks:
  mail:
    external: true
    driver: bridge